apiVersion: v1
kind: Pod
metadata:
  name: cccr-configmap-pod
spec:
  containers:
  - image: c1t1d0s7/cccr:custport
    name: cccr
    env:
    - name: NODE_PORT
      valueFrom:
        configMapKeyRef:
          name: pod-options
          key: nodeport
    - name: MESSAGE
      valueFrom:
        configMapKeyRef:
          name: pod-options
          key: message
    args: 
    - $(MESSAGE)
    ports:
    - containerPort: 8080
      protocol: TCP
