apiVersion: v1
kind: Pod
metadata:
  name: cccr-arg-pod
spec:
  containers:
  - image: c1t1d0s7/cccr
    name: cccr
    args:
    - "Customized Hello World!"
    ports:
    - containerPort: 8080
      protocol: TCP
