apiVersion: v1
kind: PersistentVolume
metadata:
  name: cccr-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs-volume
    server: 192.168.64.18
